server:
  port: 8085

spring:
  application:
    name: tour-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tourdb
    username: postgres
    password: Sunavya@1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      locationService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      lodgingService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      transportService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s


  retry:
    instances:
      locationService:
        maxAttempts: 3
        waitDuration: 2s

      lodgingService:
        maxAttempts: 3
        waitDuration: 2s

      transportService:
        maxAttempts: 3
        waitDuration: 2s
