spring.application.name=auth-service

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=Sunavya@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.forward-headers-strategy=framework

springdoc.swagger-ui.use-root-path=true

# Eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka

# JWT
jwt.secret=ThisIsMyVerySecretKeyForJwtAuthentication12345678901234567890
jwt.expiration=3600000

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
