spring.application.name=transport-service

server.port=${PORT:8084}

# Database
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.forward-headers-strategy=framework
springdoc.use-management-port=false

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

spring.cloud.config.enabled=false

logging.level.com.transport=DEBUG

# Railway Eureka hostname
eureka.instance.hostname=${EUREKA_HOSTNAME}
