spring.application.name=api-gateway

server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Gateway
spring.cloud.gateway.server.webmvc.discovery.locator.enabled=true
spring.cloud.gateway.server.webmvc.discovery.locator.lower-case-service-id=true

#Route
spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/auth/**

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
