spring.application.name=api-gateway

server.port=8765

# Eureka

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.client.service-url.defaultZone=http://service-registry:8761/eureka

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

server.forward-headers-strategy=framework

#jwt
jwt.secret=ThisIsMyVerySecretKeyForJwtAuthentication12345678901234567890
jwt.expiration=3600000

# Routes

# Auth Swagger
spring.cloud.gateway.server.webmvc.routes[0].id=auth-swagger
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/auth/v3/api-docs,/v3/api-docs

# Auth API
spring.cloud.gateway.server.webmvc.routes[1].id=auth-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/auth/**

# Tour Swagger (put before Tour API route)
spring.cloud.gateway.server.webmvc.routes[2].id=tour-service-swagger
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://TOUR-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/tours/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=RewritePath=/api/tours/v3/api-docs,/v3/api-docs

# Tour API
spring.cloud.gateway.server.webmvc.routes[3].id=tour-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://TOUR-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/tours/**

# Location Swagger
spring.cloud.gateway.server.webmvc.routes[4].id=location-swagger
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://LOCATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/locations/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=RewritePath=/api/locations/v3/api-docs,/v3/api-docs

# Location
spring.cloud.gateway.server.webmvc.routes[5].id=location-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://LOCATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/locations/**

# Lodging Swagger
spring.cloud.gateway.server.webmvc.routes[6].id=lodging-swagger
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://LODGING-SERVICE
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/lodgings/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[6].filters[0]=RewritePath=/api/lodgings/v3/api-docs,/v3/api-docs

# Lodging
spring.cloud.gateway.server.webmvc.routes[7].id=lodging-service
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://LODGING-SERVICE
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/lodgings/**

# Transport Swagger
spring.cloud.gateway.server.webmvc.routes[8].id=transport-swagger
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://TRANSPORT-SERVICE
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/transports/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[8].filters[0]=RewritePath=/api/transports/v3/api-docs,/v3/api-docs

# Transport
spring.cloud.gateway.server.webmvc.routes[9].id=transport-service
spring.cloud.gateway.server.webmvc.routes[9].uri=lb://TRANSPORT-SERVICE
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/api/transports/**

# Booking Swagger
spring.cloud.gateway.server.webmvc.routes[10].id=booking-swagger
spring.cloud.gateway.server.webmvc.routes[10].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/api/bookings/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[10].filters[0]=RewritePath=/api/bookings/v3/api-docs,/v3/api-docs

# Booking
spring.cloud.gateway.server.webmvc.routes[11].id=booking-service
spring.cloud.gateway.server.webmvc.routes[11].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.server.webmvc.routes[11].predicates[0]=Path=/api/bookings/**

# Payment Swagger
spring.cloud.gateway.server.webmvc.routes[12].id=payment-swagger
spring.cloud.gateway.server.webmvc.routes[12].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[12].predicates[0]=Path=/api/payments/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[12].filters[0]=RewritePath=/api/payments/v3/api-docs,/v3/api-docs

# Payment
spring.cloud.gateway.server.webmvc.routes[13].id=payment-service
spring.cloud.gateway.server.webmvc.routes[13].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[13].predicates[0]=Path=/api/payments/**

# Notification Swagger
spring.cloud.gateway.server.webmvc.routes[14].id=notification-swagger
spring.cloud.gateway.server.webmvc.routes[14].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[14].predicates[0]=Path=/api/notifications/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[14].filters[0]=RewritePath=/api/notifications/v3/api-docs,/v3/api-docs

# Notification
spring.cloud.gateway.server.webmvc.routes[15].id=notification-service
spring.cloud.gateway.server.webmvc.routes[15].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[15].predicates[0]=Path=/api/notifications/**

##############################################
# Swagger UI
##############################################

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=Tour Service
springdoc.swagger-ui.urls[1].url=/api/tours/v3/api-docs

springdoc.swagger-ui.urls[2].name=Location Service
springdoc.swagger-ui.urls[2].url=/api/locations/v3/api-docs

springdoc.swagger-ui.urls[3].name=Lodging Service
springdoc.swagger-ui.urls[3].url=/api/lodgings/v3/api-docs

springdoc.swagger-ui.urls[4].name=Transport Service
springdoc.swagger-ui.urls[4].url=/api/transports/v3/api-docs

springdoc.swagger-ui.urls[5].name=Booking Service
springdoc.swagger-ui.urls[5].url=/api/bookings/v3/api-docs

springdoc.swagger-ui.urls[6].name=Payment Service
springdoc.swagger-ui.urls[6].url=/api/payments/v3/api-docs

springdoc.swagger-ui.urls[7].name=Notification Service
springdoc.swagger-ui.urls[7].url=/api/notifications/v3/api-docs
